neutralinojs/neutralinojs.github.io

docs/api/storage.md
It contains documentation for newer features added with Neutralinojs v1.0.3-alpha release.
=> storage module docs added.

docs/api/settings.md
* made some changes for to enhance readablility, 
* added sample code example, for easy understanding.
=> update to settings.md

README.md, contribution.md, docs/other/changelog.md, hacktoberfest/index.html
This contains docs for new features published in 1.0.4-alpha release
=> [added] settings.json & contribution guide, [updated] readme, changelog

index.html
Fixes #14 
Also removed some whitespace at the end of lines (thank my editor!)
=> Add changelog link

docs/other/changelog.md
Added release version 1.0.5 to changelog along with a link to download.
=> add release version v1.0.5 to changelog

README.md
=> Added changelog to readme

docs/gettingstarted/quickstart.md
added download location to documentation
=> added download location to documentation

assets/css/main.css, index.html
=> Change color is yellow which is button

index.html
i think button people can see easy
=> update tag a href view log to button

assets/css/main.css, index.html
=> Make view change log color the same as button color

docs/api/computer.md, docs/api/filesystem.md, docs/api/os.md, docs/api/settings.md, docs/api/storage.md, docs/configuration/settings.json.md, docs/gettingstarted/firstapp.md, docs/gettingstarted/quickstart.md, docs/other/changelog.md
Grammar changes to certain files
=> Changes to md files

docs/api/computer.md, docs/api/filesystem.md, docs/api/os.md
These are the changes done in docs.
=> Updates to docs

docs/api/settings.md, docs/api/storage.md
These are the changes done in docs.
=> docs changes

docs/other/changelog.md
Also, I updated some dates that were just copied from previous versions.
=> Added v1.2.0 pre-release to the changelog

docs/api/computer.md
Updated the os.getRamUsage() to computer.getRamUsage() at line 5
=> Updated the os.getRamUsage to computer.getRamUsage

docs/api/computer.md
=> Fixed spelling error in computer.md

docs/configuration/neutralino.config.json.md
Fixed a typo on line 31 (vairables -> variables)
=> Fixed typo

contribution.md
Fixing some typos, cleaning up the text, and fixing some grammatical mistakes.
=> Typos, cleaning up, and grammatical mistakes

docs/api/storage.md
=> Remove incorrect curly brace

docs/contributing/framework-developer-guide.mdx
This PR does improvements on the issue no #174 
@shalithasuranga Sir can you please review and merge the PR if this looks good to you
=> Updated redirection link

docs/api/extensions.md
Changed "extensions has" to "extensions have".
=> GetStats Description Verb Typo

docs/contributing/committers.md
Thanks @shalithasuranga :heart:
Grateful to be a part of such young, small yet strong community. Have been enjoying the last couple of weeks, contributing code to world's code. Glad I met you and @DEVLOPRR. Thanks for being my potential mentors.
=> Add myself to committers list :heart:

docs/how-to/use-a-frontend-library.md
Pertains to issue #184 
Updated the folder name of frontend part of the application from <code>litepy-react</code>  to  <code>myapp-react</code>
@pathange-s Sir it would be nice if you review and merge it
=> Updated use-a-frontend-library.md

docs/cli/internal-cli-arguments.md
=> Added missing internal CLI arguments

docs/contributing/framework-developer-guide.mdx
- Mentioned what ``python scripts/bz.py`` command does. Refer [this](https://discord.com/channels/869948661084340265/869948661906436128/962411022747066488) from Neutralinojs discord server.
- Reduced font size of Debian, Fedora and Arch sections under Linux to show that they are subheadings under Linux.
=> Improved readability and fixed a typo

docs/api/extensions.md
Pertains to #197 
@shalithasuranga Pls review and merge
=> Updated extensions.md

README.md, docs/contributing/frequently-asked-questions.md, sidebars.js
Created template with a sample question for FAQs section.
=> Add frequently asked questions section

docs/contributing/committers.md
It has been amazing interacting, learning from my betters, and contributing what little I can to the community. Really looking forward to getting more involved and contributing my best to this amazing community. Thanks @shalithasuranga @DEVLOPRR @danidre14 and @pathange-s for helping me learn and contribute. 
P. S. Feels surreal.
=> Add myself to the commiters list🧡 🤍

docs/contributing/frequently-asked-questions.md
Documents [this](https://github.com/neutralinojs/neutralinojs-cli/issues/64) issue.
=> Add yarn installation queries under FAQs

docs/contributing/framework-developer-guide.mdx
=> Update client library project structure

src/pages/index.js
- This method of preventing cache is not the best way. This does cache the image / file but fools the browser that the cached image is not the fetched one. Best way to disable browser cache for particular elements is mentioned [here](https://stackoverflow.com/a/728685/16317465). Till this gets implemented, the current code change will serve the purpose
=> cached animation loading fix

docs/api/os.md
For now I've provided string examples, but it maybe worth combining an example with the getPath function too so that people can see how those could work together.
=> Add info about how to use the defaultPath option.

src/pages/index.js
I have centered the heading of the build part and made thr paragraph arranged properly with the section.
=> Changed the UI of the main page index.js 

README.md
=> modified:   README.md, Correcting a grammer mistake

docs/api/os.md
Change infos about os.showOpenDialog and os.showSaveDialog, as a bugfix of #980 .
=> Change informations about system dialogs

docs/contributing/framework-developer-guide.mdx
The current mac command for testing the app is only for intel chips, so I added a command for the arm chip so that M1 & M2 chips can also test the app.
=> Added testing command for the apple chip.

docs/contributing/framework-developer-guide.mdx
=> Add dev dependencies in framework guide docs for Fedora 

docs/configuration/project-structure.md
=> Update project-structure.md: Fixed capitalisation.

docs/contributing/framework-developer-guide.mdx
Small tweaking in a sentence in the documentation.
=> grammatically updated the documentation

docs/contributing/committers.md
Fixes #282 
Added https://github.com/ratatoeskr666 in committers.md file.
=> docs: added new committer's profile in committers.md

docs/distribution/overview.md
- Updated the build release table to add macOS binaries
- Changed `x64` to the correct `x86-64`
=> Docs: Update overview.md

docs/api/custom.md
=> Added Explainations for the custom API

docs/api/computer.md
=> Update computer.md: s/kernelInfo/osInfo/

docs/getting-started/your-first-neutralinojs-app.mdx
=> fix: getting started docs fixed

docs/configuration/neutralino.config.json.md
docs for pull request [#244](https://github.com/neutralinojs/neutralinojs-cli/pull/244)
=> Docs for dynamic build path

docs/configuration/neutralino.config.json.md
docs for pr [#253](https://github.com/neutralinojs/neutralinojs-cli/pull/253)
=> docs for ignore file feature

src/pages/index.js
made small but meaning changes to the docs in various places.
=> Grammatically updated tech docs

docs/api/app.md, docs/api/clipboard.md, docs/api/computer.md, docs/api/custom.md, docs/api/debug.md, docs/api/error-codes.md, docs/api/events.md, docs/api/extensions.md, docs/api/filesystem.md, docs/api/global-variables.md, docs/api/init.md, docs/api/os.md, docs/api/overview.md, docs/api/storage.md, docs/api/updater.md, docs/api/window.md, src/theme/DocItem/TOC/Desktop/index.js
=> FIX: max heading level set to 3/2 for toc

src/pages/styles.module.css
hey @shalithasuranga 
i am trying to change the colour of the link to installing neutralinojs on the web page.
#321 
please tell me if this change will successfully resolve the issue or not. if it wont resolve the issue let me know as well. i would like to resolve this issue my self. if not on this try, then i will try again with a different method. thank you.
=> responding to the issue #321(We need to change the colour of the link to install neutralino js)

docusaurus.config.js
I have made the changes for twitter link. Fix #338
=> Updated Twitter link in docusaurus.config.js

docs/contributing/framework-developer-guide.mdx
This PR adds a concise guide for adding a test case
=> GSoC2024: added guide for adding a test case

docusaurus.config.js
issue #349
linkedin link added on webpage
=> linkedin link added

src/pages/styles.module.css
Fixed the issue #351 
this PR resolves the issue if the alignment issue of the CodeBlockLine(the installation command for the neutralinojs) for the mobile views.
the resolved issue screenshots are:
Before:
After:
If this PR matches your requirement then merge this PR as soon as possible and as per your convenience.
=> Fix the alignment issue for CodeBlockLine

docs/api/window.md
A follow-up to https://github.com/neutralinojs/neutralino.js/pull/120 that describes the new argument and adds a new code example.
=> 📝 Document the new argument in window.setDraggableRegion

docs/contributing/framework-developer-guide.mdx
closes #365 
I have updated some docs for smoothly setting the up main repo.
=> Framework Developer Guide updated 

src/pages/resources.js
Adds my template with Vite, Svelte, and TypeScript. Perfect for quickly making good apps.
https://github.com/CosmoMyzrailGorynych/neutralino-svelte-typescript-template
=> Add neutralino-svelte-typescript-template to resources.js

docs/contributing/committers.md
changes  `- [Rahul Kumar](https://github.com/rahulptl165)`
=> added my name and GitHub profile link

docusaurus.config.js
Fixes #373. Added a new 'Socials' group to the footer, improving organization and reducing clutter.
=> Enhance Footer
