neutralinojs/neutralinojs.github.io

index.html

Changed to "In electron and NWjs you have to install NodeJs and hundreds of dependency libraries. Embedded Chromium and Node creates large overhead and makes even simple apps like “hello world” considerable in size. Neutralino offers a solution for this issue."

Simple text change on website #22

---

docs/other/committers.md

Relates to issue #83 - I assumed you wanted the link to go to the user's github page rather than his "kache" repo. Also I was unsure of his "PMC" status so I left it off.

Add Kasun Vithanage as committer

---

docs/community/committers.md

Addresses #138 .
Added new entry corbane to the committers list.
@shalithasuranga please have a look.

Added new entry corbane to the committers list

---

docs/api/init.md

Changed `os.showMessage` to `os.showMessageBox` to match actual API in the `os` namespace. Confirmed this check on both the documentation:  https://neutralino.js.org/docs/api/os/#osshowmessageboxtitle-content-choice-icon and on the v3 specifications: https://github.com/neutralinojs/v2-client-specification#os-done

Incorrect API Sample Code Fixes

---

docs/api/app.md
docs/api/os.md

The open function seems to have been moved to the `os` namespace. `Neutralino.app.open` is not a function anymore as far as I can tell.

Fix: open function moved from 'app to 'os' namespace. Fix for docs.

---

docs/api/filesystem.md

There were wrong params in documentation. filesystem.readFile() accept only one argument - the filename.

Change docs about filesystem.readFile

---

docs/how-to/extensions-overview.md

Closes https://github.com/neutralinojs/neutralinojs/issues/801
Extension ID's cannot contain dashes or other special characters. If they do the websocket connection wont work.
It was really hard to figure this out (took me like 4 - 5 hours). I don't know C++ but I figured out how to compile neu, peppered debug logs everywhere, tried a bunch of different things, and eventually figured it out. Hopefully this note will save others in the future!

docs: extension id characters

---

docs/contributing/framework-developer-guide.mdx

1. Removed libayatana-appindicator from the command as it is no longer a hard dependency.
2. Added dependency install command for arch linux since the library names are a bit different.
3. Replaced the legacy build script installation with the buildZri python script.
I tried to edit the doc to represent the latest workflow.

updated to the latest workflow, added command for arch linux

---

src/pages/index.js

- On some browsers, because pages gets cached, the animation doesn't reload with F5 (though it reloads with `ctrl+shift+r`). Note that the previous implementation worked fine locally but not on the webpage. The current implementation works fine locally and needs a test on webpage.

Reload animation of F5

---

docs/api/filesystem.md

This change becomes vital, if the pull request [Update filesystem.getStats(path) to fetch last modified time](https://github.com/neutralinojs/neutralinojs/pull/877) gets merged.

Update `filesystem.getStats` return Object to include `createdAt` and `modifiedAt`

---

docs/configuration/neutralino.config.json.md

`Windows 10 / Opera GX` in case some os/browser handles links differently

Fixed broken doc links

---

docs/configuration/neutralino.config.json.md

`globalVariables` is actually an object. Haven't found an example if it works with arrays, but correct me if im wrong

Changed type for neutralino.config.json docs

---

docs/contributing/framework-developer-guide.mdx

Added the requirement of "Windows SDK" to the Visual Studio IDE installation in the Windows part.

Improve the Windows part of the framework developer guide

---

docs/api/os.md

Changed it from `let processes = await Neutralino.getSpawnedProcesses();` to `let processes = await Neutralino.os.getSpawnedProcesses();` (the `os.` was missing)

Fixed getSpawnedProcesses code example typo

---

docs/contributing/committers.md

This PR fixes #278 
Included @nicorac as Contributor in `commiters.md`

Add claudio as contributor

---

docs/distribution/overview.md

closes #299 
fixed some typos from original docs
used build paths according neutralinojs getting started app for easier navigation
tested script for all the operating systems
added documentation where it was not clear

Application packager scripts has been added in docs

---

docs/api/filesystem.md

This PR adds the newly added options for `filesystem.copy()` in the documentation

Added options for `filesystem.copy()`

---

docs/api/updater.md

`updater.install` fails with `NE_UP_UPDINER` if `filesystem` API is not allowed. This PR adds a small note that you need to allow `filesystem` and `updater` in one's `neutralino.config.json`.

Update api/updater.md with a note about required nativeAllowList strings

---

docs/configuration/neutralino.config.json.md

list new configuration details for projectRunner supported by this [PR](https://github.com/neutralinojs/neutralinojs-cli/pull/277)

chore: Update configurations details for projectRunner in docs

---

docs/configuration/neutralino.config.json.md

Was going through the docs and getting started with my first project when i noticed the `chrome` option wasn't listed as one of the available options for the `defaultMode` key in the config page!

Update neutralino config to include "chrome" default mode option

---

src/pages/resources.js

Though the title says it all, I've linked to:
[https://github.com/scanline/neutralinojs-menubar](https://github.com/scanline/neutralinojs-menubar)
in the resources section and also [https://github.com/scanline/neutralinojs-ext-vibrancy](https://github.com/scanline/neutralinojs-ext-vibrancy)

Adding neutralinojs-menubar to the resources section for the website

---

docs/getting-started/your-first-neutralinojs-app.mdx

Added instructions to the documentation for resolving the "execution of scripts is disabled on this system" error that occurs when running `neu.ps1` on Windows systems.  
- Included the `Set-ExecutionPolicy` command with an explanation of its usage.  
- Clarified how users can temporarily or permanently adjust the execution policy to avoid this issue.  
- Improves the onboarding experience for Windows users by addressing a common setup problem with Neutralinojs.

docs: Add solution for PowerShell execution policy error on Windows

---

docs/api/overview.md
docs/getting-started/your-first-neutralinojs-app.mdx

Added a new section to the API Overview explaining how to configure nativeAllowList in neutralino.config.json. This helps developers understand how to enable specific native APIs securely.

Add security configuration section to API overview

---

src/pages/resources.js

* created a plugins array of object to store name, description, and git repository and then displayed this details on the resources page.

Added plugins section on resource page

---

docs/api/clipboard.md

Neutralinojs now supports HTML clipboard operations, enabling rich text and formatted content handling across different platforms.
- Added documentation for `writeHTML()` clipboard API method
- Added documentation for `readHTML()` clipboard API method

Added documentation for HTML clipboard API support

---

docs/api/events.md

Modified ``Event types`` table in ``events.md`` to include ``timestamp`` field in the ``watchFile`` event.

Added docs for timestamp field in watchFile event

---

src/pages/resources.js

We've made a [template](https://github.com/Cloudwerk/neutralinojs-vite-react-ts) for using Vite in combination with React and Typescript for building Neutralino Apps.
Consider adding it to the homepage :)

Add vite-react-ts template
